import { create } from 'zustand';

export const useCommandCenter = create<any>((set) => ({
  isOpen: false,
  open: () => set({ isOpen: true }),
  close: () => set({ isOpen: false }),
  highContrast: false,
  toggleHighContrast: () => set((s: any) => ({ highContrast: !s.highContrast })),
  narratorEnabled: false,
  toggleNarrator: () => set((s: any) => ({ narratorEnabled: !s.narratorEnabled })),
  mustPlayFullActive: false,
  setMustPlayFullActive: (v: boolean) => set({ mustPlayFullActive: v }),
  announceText: "",
  announce: (text: string) => { set({ announceText: text }); setTimeout(() => set({ announceText: "" }), 3000); },
  commandCenterNewsRatio: 0.5,
  setCommandCenterNewsRatio: (v: number) => set({ commandCenterNewsRatio: v }),
  clockFaceMode: "digital",
  setClockFaceMode: (v: string) => set({ clockFaceMode: v }),
  triggerMediaEngineReset: () => {},
  
  pacingPreset: "balanced",
  setPacingPreset: (v: string) => set({ pacingPreset: v }),
  watchdogEnabled: true,
  setWatchdogEnabled: (v: boolean) => set({ watchdogEnabled: v }),
  showPlayerUI: true,
  setShowPlayerUI: (v: boolean) => set({ showPlayerUI: v }),
  applyToExport: false,
  setApplyToExport: (v: boolean) => set({ applyToExport: v }),
  stallTimeoutSecs: 30,
  setStallTimeoutSecs: (v: number) => set({ stallTimeoutSecs: v }),
  offlineRetryDelaySecs: 30,
  setOfflineRetryDelaySecs: (v: number) => set({ offlineRetryDelaySecs: v }),
  maxPlayedHistory: 500,
  setMaxPlayedHistory: (v: number) => set({ maxPlayedHistory: v }),
  savedPresets: {},
  savePreset: (name: string) => {},
  loadPreset: (name: string) => {},
  deletePreset: (name: string) => {},
  guideTheme: "liberty-gold",
  setGuideTheme: (v: string) => set({ guideTheme: v }),
  triggerPreviewGuide: () => {},
  livePeekDurationMins: 5,
  setLivePeekDurationMins: (v: number) => set({ livePeekDurationMins: v }),
  midRollCadenceMins: 15,
  setMidRollCadenceMins: (v: number) => set({ midRollCadenceMins: v }),
  livePriorityActive: false,
  setLivePriorityActive: (v: boolean) => set({ livePriorityActive: v }),
  probesEnabled: false,
  setProbesEnabled: (v: boolean) => set({ probesEnabled: v }),
  healthScore: null,
  scoreHistory: [],
  tierEnteredAt: null,
  autoCalibrateRemainingSecs: null,
  triggerAutoCalibrate: () => {},
  triggerExportLog: () => {},
  registerOpenDiagnosticsPanel: (cb: () => void) => {},
  uiScale: 1.0,
  setUiScale: (v: number) => set({ uiScale: v }),
  ajBroadcastMode: false,
  setAjBroadcastMode: (v: boolean) => set({ ajBroadcastMode: v }),
  ajPipAutoResize: true,
  setAjPipAutoResize: (v: boolean) => set({ ajPipAutoResize: v }),
  ccMode: "easy",
  setCcMode: (v: string) => set({ ccMode: v }),
  newsOverrideMode: 'auto',
  setNewsOverrideMode: (mode: 'auto' | 'force_on' | 'force_off') => set({ newsOverrideMode: mode }),
}));
