import { useState, useEffect } from 'react';

export interface BroadcastSegment {
  identifier: string;
    title: string;
      start: number;
        duration: number;
          thumbBase: string;
            showId: string;
              addedDate?: string;
              }

              export interface NetworkRundown {
                channelId: string;
                  network: string;
                    segments: BroadcastSegment[];
                    }

                    export function useStaticRundown() {
                      const [rundown, setRundown] = useState<NetworkRundown[]>([]);
                        const [loading, setLoading] = useState(true);

                          useEffect(() => {
                              let isMounted = true;
                                  const fetchRundown = () => {
                                        setRundown([]);
                                              setLoading(true);

                                                    // Time-aware logic: if before 4:00 PM, use yesterday's rundown
                                                          const now = new Date();
                                                                const hour = now.getHours();
                                                                      const ingestionHour = 16; // 4:00 PM

                                                                            let targetDate = new Date(now);
                                                                                  if (hour < ingestionHour) {
                                                                                          // Before 4:00 PM: use yesterday's archive
                                                                                                  targetDate.setDate(targetDate.getDate() - 1);
                                                                                                        }

                                                                                                              const dateString = targetDate.toISOString().split('T')[0];
                                                                                                                    const cacheBuster = `?v=${dateString}`;

                                                                                                                          const primaryController = new AbortController();
                                                                                                                                const primaryTimeout = setTimeout(() => primaryController.abort(), 8000);

                                                                                                                                      fetch(`/data/daily-rundown.json${cacheBuster}`, { signal: primaryController.signal })
                                                                                                                                              .then(async (res) => {
                                                                                                                                                        if (!res.ok) throw new Error(`HTTP_${res.status}: Static JSON not found`);
                                                                                                                                                                  const data = await res.json();
                                                                                                                                                                            if (!Array.isArray(data)) throw new Error('Invalid JSON shape: expected array');

                                                                                                                                                                                      const totalSegments = data.reduce(
                                                                                                                                                                                                  (acc: number, net: NetworkRundown) => acc + (net.segments?.length || 0),
                                                                                                                                                                                                              0
                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                  if (totalSegments === 0) throw new Error('Static file contains 0 segments');

                                                                                                                                                                                                                                            return data as NetworkRundown[];
                                                                                                                                                                                                                                                    })
                                                                                                                                                                                                                                                            .then((data) => {
                                                                                                                                                                                                                                                                      if (isMounted) {
                                                                                                                                                                                                                                                                                  setRundown(data);
                                                                                                                                                                                                                                                                                              setLoading(false);
                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                                                                        .catch((err) => {
                                                                                                                                                                                                                                                                                                                                  if (!isMounted) return;
                                                                                                                                                                                                                                                                                                                                            console.error(`Static rundown unusable (${err.message}). Falling back to live API...`);

                                                                                                                                                                                                                                                                                                                                                      const fallbackController = new AbortController();
                                                                                                                                                                                                                                                                                                                                                                const fallbackTimeout = setTimeout(() => fallbackController.abort(), 8000);

                                                                                                                                                                                                                                                                                                                                                                          fetch(`/api/rundown?date=${dateString}`, { signal: fallbackController.signal })
                                                                                                                                                                                                                                                                                                                                                                                      .then(async (res) => {
                                                                                                                                                                                                                                                                                                                                                                                                    if (!res.ok) throw new Error(`HTTP_${res.status}: Live API failed`);
                                                                                                                                                                                                                                                                                                                                                                                                                  const data = await res.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                if (!Array.isArray(data)) throw new Error('Invalid live API response shape');
                                                                                                                                                                                                                                                                                                                                                                                                                                              return data as NetworkRundown[];
                                                                                                                                                                                                                                                                                                                                                                                                                                                          })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .then((data) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (isMounted) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setRundown(data);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setLoading(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .catch((fallbackErr) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (isMounted) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.error('Critical: Both static and live rundowns failed:', fallbackErr);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setLoading(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .finally(() => clearTimeout(fallbackTimeout));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .finally(() => clearTimeout(primaryTimeout));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fetchRundown();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Refetch every 24 hours
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const intervalRef = setInterval(fetchRundown, 24 * 60 * 60 * 1000);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        isMounted = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              clearInterval(intervalRef);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setRundown([]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }, []);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return { rundown, loading };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }